### PR TITLE
[EMCAL-1118] Add QC node workflow for EMCAL pedestal calibration QC

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
@knopers8 @teo Please review and merge if OK!

**Comment by knopers8** [comment]
Do you need it in prod?

**Review by knopers8 — APPROVED** [review]

**Comment by mfasDa** [comment]
@knopers8 Yes, starting from the next FLP Suite release we should be ready to commission the pedestal run at P2. This PR relates to the dedicated QC task.

**Comment by knopers8** [comment]
Ah, so by the next FLP suite release do you mean 1.27.0?

**Comment by mfasDa** [comment]
Yes, because it still needs a commit in O2 which was merged this morning, and a commit in QualityControl which was merged after the release was tagged.

**Pull request merged**
