### PR TITLE
FIT: simple raw2digits + qc workflow for all three FIT subdetectors

### PR DESCRIPTION
**Pull request by afurs**

### CODE REVIEW

**Comment by afurs** [comment]
Hello @teo , could you take a look to this PR?

**Review by knopers8 — CHANGES_REQUESTED** [review]
all seems correct, but could you please add the new scripts to `generate-all-dpl-workflows.sh`?

**Comment by afurs** [comment]
@knopers8 hello, ok, it is done

**Review by knopers8 — APPROVED** [review]

**Comment by knopers8** [comment]
Thanks!

**Pull request merged**
