### PR TITLE
Address the change of check runner name binary

### PR DESCRIPTION
**Pull request by Barthelemy**
by adding a number of tasks and workflows

### CODE REVIEW

**Comment by graduta** [comment]
You mentioned `readout-qc-1` should never be used anymore. Could we remove it from workflow?

**Comment by Barthelemy** [comment]
I did not express myself correctly. If someone uses v0.5.0 then they need to use it.

**Comment by Barthelemy** [comment]
@knopers8

**Comment by knopers8** [comment]
It looks like it should work, assuming that the checker name corresponds to the check names which will be running in that configuration.

**Comment by graduta** [comment]
This is related to the blocker: OCTRL-189. Could we merge it so that we can test it?

**Comment by Barthelemy** [comment]
I cannot merge it.

**Comment by awegrzyn** [comment]
This PR broke FLP Suite CI as it uses `readout-qc-v0.5.0` during the tests phase...

**Comment by awegrzyn** [comment]
I tried `readout-qc-v0.7.0` but only what I get is `DeadlineExceeded`

**Comment by teo** [comment]
Ouch, looks like the rename did it. @Barthelemy @knopers8 can we make it easy and avoid this rename?

**Comment by knopers8** [comment]
If you mean the file rename, then that is okay with me.

**Comment by Barthelemy** [comment]
we can

**Comment by Barthelemy** [comment]
https://github.com/AliceO2Group/ControlWorkflows/pull/7

**Pull request merged**
