### PR TITLE
CPV pedestal calibration workflow + small fixes

### PR DESCRIPTION
**Pull request by sevdokim**
Hello! New CPV pedestal calibration workflow added + more outputs are added to cpv-compressor and cpv-qc-compressor.

### CODE REVIEW

**Comment by sevdokim** [comment]
Ouups, I somehow picked up Teo's commits... Is it a problem?

**Comment by vascobarroso** [comment]
> Ouups, I somehow picked up Teo's commits... Is it a problem?

I don't think so, I usually see those commits in PRs (not sure why). @teo  ?

**Comment by teo** [comment]
> > Ouups, I somehow picked up Teo's commits... Is it a problem?
> 
> I don't think so, I usually see those commits in PRs (not sure why). @teo ?

I'll take care of this.

**Comment by teo** [comment]
Review continues at https://github.com/AliceO2Group/ControlWorkflows/pull/149

**Pull request closed without merging**
