### PR TITLE
Update labels for the workflows

### PR DESCRIPTION
**Pull request by Barthelemy**
@vascobarroso @teo @knopers8 @graduta Please let me know what you think. To me it clearer this way.

### CODE REVIEW

**Comment by vascobarroso** [comment]
@Barthelemy this is fine for me. I would just rename the panel from `aliecs_Workflows` to `AliECS_Workflows`

**Comment by graduta** [comment]
> @Barthelemy this is fine for me. I would just rename the panel from `aliecs_Workflows` to `AliECS_Workflows`

Naming it `AliECS_Workflows` will trigger the old convention of camelCase naming and it will be displayed as `Ali ECS Workflows`
I kept both conventions for now for backwards compatibility.

**Comment by vascobarroso** [comment]
> > @Barthelemy this is fine for me. I would just rename the panel from `aliecs_Workflows` to `AliECS_Workflows`
> 
> Naming it `AliECS_Workflows` will trigger the old convention of camelCase naming and it will be displayed as `Ali ECS Workflows` I kept both conventions for now for backwards compatibility.

@graduta, I see. What about ALIECS ?

**Comment by graduta** [comment]
> > > @Barthelemy this is fine for me. I would just rename the panel from `aliecs_Workflows` to `AliECS_Workflows`
> > 
> > 
> > Naming it `AliECS_Workflows` will trigger the old convention of camelCase naming and it will be displayed as `Ali ECS Workflows` I kept both conventions for now for backwards compatibility.
> 
> @graduta, I see. What about ALIECS ?

`ALIECS` will stay as `ALIECS`

**Comment by vascobarroso** [comment]
@Barthelemy please rename the panel to "ALIECS_Workflows". Thanks!

**Review by knopers8 — APPROVED** [review]

**Comment by Barthelemy** [comment]
I have done the renaming

**Review by vascobarroso — APPROVED** [review]

**Pull request merged**
