### PR TITLE
TPC IDC lifetime fix

### PR DESCRIPTION
**Pull request by martenole**
Please check @davidrohr and @matthias-kleiner 
I assume that also the `jit/tpc-idc-merger` requires a fix, but I was not sure how

### CODE REVIEW

**Comment by martenole** [comment]
Hi @vascobarroso could this be merged please?

**Review by vascobarroso — APPROVED** [review]

**Comment by vascobarroso** [comment]
@martenole done. Will be part of the next FLP Suite release, please let me know if it should be deployed sooner.

**Comment by martenole** [comment]
Thanks @vascobarroso ! I think it would be good to have it in the current FLP suite. If there is time tomorrow or Friday for a global synthetic run we could try again without the `DPL_WORKAROUND_DO_NOT_CHECK_FOR_CORRECT_WORKFLOW_LIFETIMES` and see if that works then. If not, we might be able to provide another fix before the next update

**Comment by vascobarroso** [comment]
@martenole this change is now at P2. I let you organize the test to check if it helps or not.

**Pull request merged**
