### PR TITLE
add extra buffer protection in tof-compressor

### PR DESCRIPTION
**Pull request by noferini**
This is to add an extra protection to tof-compressor as suggested by @preghenella 

It adds an extra buffer before the encoding of compressed data, preventing to go out of memory in case the compressed size is larger than uncompressed (such a case is excluded for sure beyond the tolerance added here)
To be ported at P2 as soon as possible

@preghenella, can you also comment on this?

### CODE REVIEW

**Comment by noferini** [comment]
In the meanwhile, I also ran some tests. We can merge it and port it to P2

**Comment by preghenella** [comment]
looks ok to me

**Comment by noferini** [comment]
Validated also at P2 in a cosmic run

**Comment by noferini** [comment]
Since we collected one TF producing an error and this is not enough to protect I close this PR (we will add all protections in one O2 PR once ready)

**Pull request closed without merging**
