### PR TITLE
tof test modes

### PR DESCRIPTION
**Pull request by noferini**

### CODE REVIEW

**Comment by noferini** [comment]
This is the last tuning of TOF workflow validated in the last days (1 cosmic run of 14h)

**Comment by vascobarroso** [comment]
@noferini should this be added in next Monday's SW deployment ? Immediately to the current FLP Suite at P2 ?

**Comment by noferini** [comment]
Hi @vascobarroso , this is required to join global run eith TOF. As soon as possible is the best for us

**Review by vascobarroso — APPROVED** [review]

**Comment by vascobarroso** [comment]
@noferini just to be sure, this is compatible with the current O2 version at P2 right ?

**Pull request merged**
