### PR TITLE
[OCTRL-447] Documentation of automatic workflow template generation

### PR DESCRIPTION
**Pull request by knopers8**
@teo @miltalex @vascobarroso @Barthelemy It would be great if one of you tried to follow it.

### CODE REVIEW

**Comment by Barthelemy** [comment]
The script did not work on Mac. I think that it is fine but you could add a sentence about it.

**Comment by knopers8** [comment]
Thanks, I will apply your comments. The script probably doesn't work on mac because of the differences in `sed`. Indeed it requires a comment at least.

**Comment by knopers8** [comment]
OK, added a bit of explanation on `readout-dataflow` and a comment about `sed` on Mac.

**Comment by knopers8** [comment]
Can we merge it if there are no other comments?

**Review by teo — APPROVED** [review]

**Pull request merged**
