### PR TITLE
Large upgrade for FIT

### PR DESCRIPTION
**Pull request by afurs**
1. raw2digit
2. raw2digit+pipeline
2. raw2digit+dispatcher+qc
3. raw2digit+dispatcher+qc+pipeline
4. FT0: raw2digit+dispatcher+qc+postprocessing
5. FT0: raw2digit+dispatcher+qc+postprocessing+pipeline

Static cycle duration options deleted from yamls

### CODE REVIEW

**Comment by afurs** [comment]
Hello @teo @vascobarroso , could you take a look to this PR, please? It is quite large...

**Comment by vascobarroso** [comment]
I think we need to enlist @knopers8 as well

**Review by knopers8 — APPROVED** [review]
I had a look at the QC config files, scripts and workflow templates (skipped task templates). It looks correct, thanks for the hard work.

**Comment by afurs** [comment]
Thanks!

**Comment by afurs** [comment]
Will it be merged with `flp-suite-v0.29.0` ?

**Comment by vascobarroso** [comment]
@afurs this has been rebased to `flp-suite-v0.29.0` and should be available at P2 in the central AliECS instance.

**Pull request merged**
