### PR TITLE
[FOCAL-12] Include pedestal QC in pedestal DA

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
@teo @knopers8 Please review!

**Comment by mfasDa** [comment]
Uses https://github.com/AliceO2Group/QualityControl/pull/1744

**Comment by Barthelemy** [comment]
The config file is not in Consul at P2: foc-padpedestal-qc-*
Thus I cannot really say, but the modification simply adds QC to this workflow.

**Comment by mfasDa** [comment]
> The config file is not in Consul at P2: foc-padpedestal-qc-*
> Thus I cannot really say, but the modification simply adds QC to this workflow.

The FOCAL FLP is configured as stand-alone FLP, thus the local consul instance is used. You find the configuration here: http://alio2-flp-focal.dyndns.cern.ch:8500/ui/alice-o2-cluster/kv/o2/components/qc/ANY/any/foc-padpedestal-qc-alio2-flp-focal/edit

**Review by Barthelemy — APPROVED** [review]

**Pull request merged**
