### PR TITLE
CTP: set max allowed input size to protect the decoder from ringing inputs

### PR DESCRIPTION
**Pull request by aferrero2707**
The `--max-input-size 700000` parameter has been added to the `o2-ctp-reco-workflow` in all the FLP workflows. The value is about 10% below the data size expected from ringing inputs.

Also added `--max-input-size-fatal true` to issue a fatal error in case large data input size is detected. The fatal error will trigger the stop of the ongoing run.

### CODE REVIEW

**Comment by aferrero2707** [comment]
@lietava @vascobarroso can you have a look? Thanks!

**Comment by lietava** [comment]
@aferrero2707 it looks ok for me.

**Review by knopers8 — APPROVED** [review]

**Comment by vascobarroso** [comment]
@aferrero2707 should this be included in this week's deployment ? If so, I can cherry pick it into the release branch.

**Comment by vascobarroso** [comment]
@lietava this was deployed yesterday so it's available in production

**Pull request merged**
