### PR TITLE
setting DPL_PIPELINE to 32 for TOF flp workflow

### PR DESCRIPTION
**Pull request by noferini**
This is to set as default the option suggested by @ktf for tof flp worflow

### CODE REVIEW

**Comment by noferini** [comment]
@knopers8 , @Barthelemy

**Comment by Barthelemy** [comment]
I don't know this option but I am fine with it.

**Review by Barthelemy — APPROVED** [review]

**Comment by noferini** [comment]
@Barthelemy , thanks a lot. Is it possible to port this change also in flp-suite-v0.94.0.
At the moment we are passing this option thorugh the environmente but it would be easier to have it as default in the control workflow.
This option help to reduce the load on the output-proxy at flp level.

**Comment by Barthelemy** [comment]
Hi, I'll let @vascobarroso and @knopers8 comment and approve your request. I am just back from holidays and I am not sure where we stand.

**Comment by vascobarroso** [comment]
@noferini I have ported this into `flp-suite-v0.94.0`.

**Comment by noferini** [comment]
Hi @vascobarroso , many thanks!
Cheers
Francesco

**Pull request merged**
