### PR TITLE
add tof match QC

### PR DESCRIPTION
**Pull request by noferini**
@Barthelemy Could you enable my repo in AliECS so that we can run a test?

### CODE REVIEW

**Comment by noferini** [comment]
Thanks, I will report here the result of the test as soon as we did it

**Comment by noferini** [comment]
Hi Bart,
qc-merger started properly and new QC merging task were added (I cannot fill them since epn workflow is still missing).
We can merge this PR.
Note that this change affect only the "emergency" configuration with compressors on epn.
At this stage we preferred not to touch the official one (we will do after the pilot beam)

**Comment by Barthelemy** [comment]
ok very good

**Comment by Barthelemy** [comment]
I have to let @vascobarroso or @knopers8 do it .

**Review by vascobarroso — APPROVED** [review]

**Comment by vascobarroso** [comment]
@noferini is this for FLP Suite v0.60.0 (to be deployed at P2 next Tuesday) or for now ?

**Comment by noferini** [comment]
@vascobarroso 
I don't know whatt are the plan for this week.
If @shahor02 and @davidrohr will manage to run tracking and matching on EPN, this PR will provided an alternative configuration to get the QC of the matched TOF-track in sync phase.
If possible/needed I would merge it to be ready in such case.
As mentioned, this PR doesn't touch the standard configuration (to avoid surprise).

**Comment by vascobarroso** [comment]
@noferini I have pushed this to the current default revision being used at P2 (after the agreement of RC).

**Pull request merged**
