### PR TITLE
Tpc krypton qc

### PR DESCRIPTION
**Pull request by rmunzer**
- Added QC node workflow for Krypton cluster qc. 
- Added Krypton cluster post-processing task to tpc-qc-post-processing-remote

### CODE REVIEW

**Comment by knopers8** [comment]
Hi, @rmunzer , the first three commits should not be in this pull request, couldl you please remove them? Also, it seems there are some conflicts after the workflows were regenerated for the upcoming flp suite release, could you please resolve them? Perhaps they need regenerating.

**Comment by knopers8** [comment]
Also, please add the new script (scripts/tpc-krypton-qcmn.sh ) to `scripts/generate-all-workflows.sh`, so it is reran for each bump.

**Comment by rmunzer** [comment]
Hi @knopers8,

thanks. I resolved the conflicts and added the scripts to generate all. I am not sure how to remove the first three commit from the Pull Request. Do I need to recreate the branch without this commit?

**Comment by knopers8** [comment]
You can for example:
```
git checkout -b tpc-krypton-qc-backup # in case you break it
git checkout tpc-krypton-qc
git rebase -i HEAD~12
# remove the accidentally brought commits in the text editor
git push -f origin tpc-krypton-qc
```

**Pull request closed without merging**
